CREATE TABLE MED_BOROUGH(OBJECTID int, CODIGO varchar, NOMBRE varchar, IDENTIFICACION varchar,LIMITEMUNICIPIOID int, SUBTIPO_COMUNACORREGIMIENTO int, SHAPEAREA numeric, SHAPELEN numeric);

CREATE TABLE MED_NEIGHBORHOOD( OBJECTID int, CODIGO varchar,  BARRIO  varchar, SUBTIPO_BARRIOVEREDA  int,
SHAPEAREA numeric, SHAPELEN numeric);


CREATE TABLE HUECOS (
CONSECUTIVO varchar, FECHA_REPORTADO date, DS_DIRECCION varchar,
       OBSERVACION varchar, LONGITUD numeric, LATITUD numeric, FECHA_EJECUCION varchar,
       CODIGO_COMUNA int, CODIGO_BARRIO int, LONGITUD_BACHE numeric, ANCHO_BACHE numeric,
       ESPESOR_BACHE numeric, AREA_BACHE numeric, VOLUMEN_BACHE numeric, TONELADAS_BACHE numeric,
       NOMBRE_COMUNA varchar, IDENTIFICACION_COMUNA varchar, NOMBRE_BARRIO varchar
)

CREATE TABLE WEATHER(
FECHA timestamp, ESTACION varchar, PRECIPITACION numeric)
